In [4]:
import numpy as np
import pandas as pd

In [5]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [6]:
data=pd.DataFrame({
    'age':[15,16,17,18,19,20],
    'studyTime':[1,2,3,2,4,3],
    'faliures':[0,1,0,2,1,0]
}).astype(float)

### Min-Max Normalization

In [7]:
scaler = MinMaxScaler()
min_max_normalized_data = scaler.fit_transform(data)
min_max_normalized_df = pd.DataFrame(min_max_normalized_data, columns=data.columns)

print("Original Data:\n", data)
print("\nMin-Max Normalized Data:\n")
display(min_max_normalized_df)

Original Data:
     age  studyTime  faliures
0  15.0        1.0       0.0
1  16.0        2.0       1.0
2  17.0        3.0       0.0
3  18.0        2.0       2.0
4  19.0        4.0       1.0
5  20.0        3.0       0.0

Min-Max Normalized Data:

   age  studyTime  faliures
0  0.0   0.000000       0.0
1  0.2   0.333333       0.5
2  0.4   0.666667       0.0
3  0.6   0.333333       1.0
4  0.8   1.000000       0.5
5  1.0   0.666667       0.0

### Z-score Normalization

In [8]:
scaler = StandardScaler()
z_score_normalized_data = scaler.fit_transform(data)
z_score_normalized_df = pd.DataFrame(z_score_normalized_data, columns=data.columns)


print("Original Data:\n", data)
print("\nZ-score Normalized Data:\n")
display(z_score_normalized_df)

Original Data:
     age  studyTime  faliures
0  15.0        1.0       0.0
1  16.0        2.0       1.0
2  17.0        3.0       0.0
3  18.0        2.0       2.0
4  19.0        4.0       1.0
5  20.0        3.0       0.0

Z-score Normalized Data:

       age  studyTime  faliures
0 -1.46385  -1.566699 -0.894427
1 -0.87831  -0.522233  0.447214
2 -0.29277   0.522233 -0.894427
3  0.29277  -0.522233  1.788854
4  0.87831   1.566699  0.447214
5  1.46385   0.522233 -0.894427

### Decimal Scaling Normalization

In [9]:
def decimal_scaling_normalize(df):
    df_scaled = df.copy()
    for column in df.columns:
        max_abs_value = df[column].abs().max()
        if max_abs_value == 0:
            df_scaled[column] = 0.0
        else:

            j = np.ceil(np.log10(max_abs_value))
            df_scaled[column] = df[column] / (10 ** j)
    return df_scaled

decimal_scaled_df = decimal_scaling_normalize(data)

print("Original Data:\n", data)
print("\nDecimal Scaled Data:\n")
display(decimal_scaled_df)

Original Data:
     age  studyTime  faliures
0  15.0        1.0       0.0
1  16.0        2.0       1.0
2  17.0        3.0       0.0
3  18.0        2.0       2.0
4  19.0        4.0       1.0
5  20.0        3.0       0.0

Decimal Scaled Data:

    age  studyTime  faliures
0  0.15        0.1       0.0
1  0.16        0.2       0.1
2  0.17        0.3       0.0
3  0.18        0.2       0.2
4  0.19        0.4       0.1
5  0.20        0.3       0.0

### Summary of Normalization Results

In [10]:
print("Original Data:\n")
display(data)

print("\nMin-Max Normalized Data:\n")
display(min_max_normalized_df)

print("\nZ-score Normalized Data:\n")
display(z_score_normalized_df)

print("\nDecimal Scaled Data:\n")
display(decimal_scaled_df)

Original Data:

    age  studyTime  faliures
0  15.0        1.0       0.0
1  16.0        2.0       1.0
2  17.0        3.0       0.0
3  18.0        2.0       2.0
4  19.0        4.0       1.0
5  20.0        3.0       0.0

Min-Max Normalized Data:

   age  studyTime  faliures
0  0.0   0.000000       0.0
1  0.2   0.333333       0.5
2  0.4   0.666667       0.0
3  0.6   0.333333       1.0
4  0.8   1.000000       0.5
5  1.0   0.666667       0.0

Z-score Normalized Data:

       age  studyTime  faliures
0 -1.46385  -1.566699 -0.894427
1 -0.87831  -0.522233  0.447214
2 -0.29277   0.522233 -0.894427
3  0.29277  -0.522233  1.788854
4  0.87831   1.566699  0.447214
5  1.46385   0.522233 -0.894427

Decimal Scaled Data:

    age  studyTime  faliures
0  0.15        0.1       0.0
1  0.16        0.2       0.1
2  0.17        0.3       0.0
3  0.18        0.2       0.2
4  0.19        0.4       0.1
5  0.20        0.3       0.0